#pragma once

#include "../compiler/tree.hpp"
#include "../utils/common.hpp"
#include "../utils/format.hpp"
#include "../utils/utils.hpp"
#include "ErrorListener.hpp"
#include "SpadeLexer.h"
#include "SpadeVisitor.h"
#include "antlr4-runtime.h"

/**
 * @brief The visitor class of the compiler which visits the parse tree generated by the parser
 */
class Visitor : public SpadeVisitor {
   private:
    /**
     * @brief The declaration tree which contains all the declarations
     */
    DeclTree *tree = null;
    /**
     * @brief Current package path the visitor is visiting
     */
    vector<Package *> currentPackages;
    /**
     * @brief Current types the visitor is visiting
     */
    vector<Type *> currentTypes;
    /**
     * @brief Current methods the visitor is visiting
     */
    vector<Method *> currentMethods;
    /**
     * @brief Current scopes the visitor is visiting
     */
    vector<Scope *> currentScopes;

    ErrorListener *listener;
    SpadeParser *parser;

    bool checkingStarted = false;

    [[noreturn]] void reportError(antlr4::Token *token, string msg) {
        listener->syntaxError(parser, token, token->getLine(), token->getCharPositionInLine(), msg,
                              std::make_exception_ptr(std::runtime_error(msg)));
        exit(-1);
    }

    [[noreturn]] void reportError(antlr4::ParserRuleContext *ctx, string msg) {
        listener->syntaxError(parser, ctx, msg);
        exit(-1);
    }

   public:
    explicit Visitor(SpadeParser *parser, ErrorListener *listener) : listener(listener), parser(parser) {}

    std::any visitSep(SpadeParser::SepContext *ctx) override {
        return null;
    }

    Type *checkType(SpadeParser::ReferenceContext *ctx) {
        auto tokens = any_cast<vector<antlr4::Token *>>(visitReference(ctx));
        DeclNode *node = null;
        for (auto token : tokens) {
            if (node == null) {
                node = tree->getRoot();
            } else {
                auto itr = std::find_if(node->getChildren().begin(), node->getChildren().end(), [&](DeclNode *node) {
                    return node->getName()->getText() == token->getText();
                });
                if (itr == node->getChildren().end())
                    reportError(ctx, "cannot find symbol");
                else
                    node = *itr;
            }

            auto name = node->getName()->getText();
            if (!name.empty() && name != token->getText()) reportError(ctx, "cannot find symbol");
        }
        try {
            return cast<Type *>(node);
        } catch (const CastError &) {
            reportError(ctx, "not a type");
        }
    }

    Type *checkType(SpadeParser::TypeContext *ctx) {
        // Todo: implement this
        return null;
    }

    void checkPermittedModifiers(DeclNode *node, vector<string> modifiers) {
        std::set<string> modStrs;
        for (auto modifier : node->getModifiers())
            for (auto modStr : modifiers)
                if (modifier->getText() != modStr)
                    reportError(modifier, "not permitted");
                else
                    modStrs.insert(modStr);

        if (modStrs.find("private") != modStrs.end()) {
            if (modStrs.find("abstract") != modStrs.end())
                reportError(DeclNode::getCtx(node), "private object cannot be abstract");
            else if (modStrs.find("final") != modStrs.end())
                reportError(DeclNode::getCtx(node), "private object cannot be final");
        } else if (modStrs.find("abstract") != modStrs.end()) {
            if (modStrs.find("final") != modStrs.end())
                reportError(DeclNode::getCtx(node), "abstract object cannot be final");
            else if (modStrs.find("static") != modStrs.end())
                reportError(DeclNode::getCtx(node), "abstract object cannot be static");
        }
    }

    void checkModifiers(Class *klass) {
        auto modifiers = klass->getModifiers();
        auto parent = klass->getParent();
        switch (parent->getKind()) {
            case DeclNode::Kind::PACKAGE:
                checkPermittedModifiers(klass, {"public", "abstract", "final"});
                break;
            case DeclNode::Kind::SCOPE:
                checkPermittedModifiers(klass, {"abstract", "final"});
                break;
            case DeclNode::Kind::TYPE:
                switch (cast<Type *>(parent)->getTypeKind()) {
                    case Type::Kind::CLASS:
                        checkPermittedModifiers(klass,
                                                {"private", "internal", "protected", "public", "abstract", "final",
                                                 "static"});
                        break;
                    case Type::Kind::INTERFACE:
                        checkPermittedModifiers(klass, {""});
                        break;
                    case Type::Kind::ENUM:
                        checkPermittedModifiers(klass, {""});
                        break;
                    case Type::Kind::ANNOTATION:
                        checkPermittedModifiers(klass,
                                                {"private", "internal", "protected", "public", "abstract", "final",
                                                 "static"});
                        break;
                }
                break;
            default:
                break;
        }
    }

    void checkModifiers(Interface *interface) {
        auto modifiers = interface->getModifiers();
        auto parent = interface->getParent();
        switch (parent->getKind()) {
            case DeclNode::Kind::PACKAGE:
                checkPermittedModifiers(interface, {"public"});
                break;
            case DeclNode::Kind::SCOPE:
                checkPermittedModifiers(interface, {""});
                break;
            case DeclNode::Kind::TYPE:
                switch (cast<Type *>(parent)->getTypeKind()) {
                    case Type::Kind::CLASS:
                        checkPermittedModifiers(interface,
                                                {"private", "internal", "protected", "public", "static"});
                        break;
                    case Type::Kind::INTERFACE:
                        checkPermittedModifiers(interface, {""});
                        break;
                    case Type::Kind::ENUM:
                        checkPermittedModifiers(interface, {""});
                        break;
                    case Type::Kind::ANNOTATION:
                        checkPermittedModifiers(interface,
                                                {"private", "internal", "protected", "public", "static"});
                        break;
                }
                break;
            default:
                break;
        }
    }

    void checkModifiers(Enum *enumClass) {
        auto modifiers = enumClass->getModifiers();
        auto parent = enumClass->getParent();
        switch (parent->getKind()) {
            case DeclNode::Kind::PACKAGE:
                checkPermittedModifiers(enumClass, {"public"});
                break;
            case DeclNode::Kind::SCOPE:
                checkPermittedModifiers(enumClass, {""});
                break;
            case DeclNode::Kind::TYPE:
                switch (cast<Type *>(parent)->getTypeKind()) {
                    case Type::Kind::CLASS:
                        checkPermittedModifiers(enumClass,
                                                {"private", "internal", "protected", "public", "static"});
                        break;
                    case Type::Kind::INTERFACE:
                        checkPermittedModifiers(enumClass, {""});
                        break;
                    case Type::Kind::ENUM:
                        checkPermittedModifiers(enumClass, {""});
                        break;
                    case Type::Kind::ANNOTATION:
                        checkPermittedModifiers(enumClass,
                                                {"private", "internal", "protected", "public", "static"});
                        break;
                }
                break;
            default:
                break;
        }
    }

    void checkModifiers(Annotation *annotation) {
        auto modifiers = annotation->getModifiers();
        auto parent = annotation->getParent();
        switch (parent->getKind()) {
            case DeclNode::Kind::PACKAGE:
                checkPermittedModifiers(annotation, {"public", "abstract", "final"});
                break;
            case DeclNode::Kind::SCOPE:
                checkPermittedModifiers(annotation, {"abstract", "final"});
                break;
            case DeclNode::Kind::TYPE:
                switch (cast<Type *>(parent)->getTypeKind()) {
                    case Type::Kind::CLASS:
                        checkPermittedModifiers(annotation,
                                                {"private", "internal", "protected", "public", "abstract", "final",
                                                 "static"});
                        break;
                    case Type::Kind::INTERFACE:
                        checkPermittedModifiers(annotation, {""});
                        break;
                    case Type::Kind::ENUM:
                        checkPermittedModifiers(annotation, {""});
                        break;
                    case Type::Kind::ANNOTATION:
                        checkPermittedModifiers(annotation,
                                                {"private", "internal", "protected", "public", "abstract", "final",
                                                 "static"});
                        break;
                }
                break;
            default:
                break;
        }
    }

    void checkModifiers(Variable *variable) {
        auto modifiers = variable->getModifiers();
        auto parent = variable->getParent();
        switch (parent->getKind()) {
            case DeclNode::Kind::PACKAGE:
                checkPermittedModifiers(variable, {"public", "final"});
                break;
            case DeclNode::Kind::SCOPE:
                checkPermittedModifiers(variable, {"final"});
                break;
            case DeclNode::Kind::TYPE:
                switch (cast<Type *>(parent)->getTypeKind()) {
                    case Type::Kind::CLASS:
                        checkPermittedModifiers(variable,
                                                {"private", "internal", "protected", "public", "final", "static"});
                        break;
                    case Type::Kind::INTERFACE:
                        checkPermittedModifiers(variable, {""});
                        break;
                    case Type::Kind::ENUM:
                        checkPermittedModifiers(variable, {""});
                        break;
                    case Type::Kind::ANNOTATION:
                        checkPermittedModifiers(variable,
                                                {"private", "internal", "protected", "public", "static"});
                        break;
                }
                break;
            default:
                break;
        }
    }

    void checkTypeParam(TypeParam *typeParam) {
        auto ctx = typeParam->getCtx();
        if (ctx->OUT() != null)
            typeParam->setVariant(TypeParam::Variant::COVARIANT);
        else if (ctx->IN() != null)
            typeParam->setVariant(TypeParam::Variant::CONTRAVARIANT);
        else {
            typeParam->setVariant(TypeParam::Variant::INVARIANT);
            if (ctx->variantOf)
                reportError(ctx->variantOf, "variant cannot be specified to an invariant type parameter");
        }

        if (ctx->variantOf)
            typeParam->setVariantOf(checkType(ctx->variantOf));
        if (ctx->defaultValue)
            typeParam->setDefaultValue(checkType(ctx->defaultValue));
    }

    Type *checkExpr(SpadeParser::ExprContext *ctx) {
        return null;
    }

    void checkVariable(Variable *variable) {
        checkModifiers(variable);
        auto nameCtx = variable->getNameCtx();
        auto valueCtx = variable->getExprCtx();

        Type *exprType = checkExpr(valueCtx);
        auto type = any_cast<Type *>(visitName(nameCtx));
        if (type == null && exprType == null)
            reportError(nameCtx, "type of the variable cannot be inferred");
        else if (type == null)
            variable->setType(exprType);
        else if (exprType == null)
            variable->setType(type);
        else {
            if (type->isSuperOf(exprType))
                variable->setType(type);  // Need to get a cast
            else
                reportError(valueCtx, "cannot be assigned");
        }
    }

    void traverseDeclNode(DeclNode *node) {
        switch (node->getKind()) {
            case DeclNode::Kind::PACKAGE: {
                auto package = cast<Package *>(node);
                currentPackages.push_back(package);
                for (auto child : package->getChildren()) traverseDeclNode(child);
                currentPackages.pop_back();
                break;
            }
            case DeclNode::Kind::SCOPE: {
                auto scope = cast<Scope *>(node);
                currentScopes.push_back(scope);
                visitBlock(scope->getCtx());
                currentScopes.pop_back();
                break;
            }
            case DeclNode::Kind::TYPE: {
                Type *type = cast<Type *>(node);
                currentTypes.push_back(type);
                switch (type->getTypeKind()) {
                    case Type::Kind::CLASS:
                        visitClassDecl(cast<Class *>(type)->getCtx());
                        break;
                    case Type::Kind::INTERFACE:
                        visitInterfaceDecl(cast<Interface *>(type)->getCtx());
                        break;
                    case Type::Kind::ENUM:
                        visitEnumDecl(cast<Enum *>(type)->getCtx());
                        break;
                    case Type::Kind::ANNOTATION:
                        visitAnnoDecl(cast<Annotation *>(type)->getCtx());
                        break;
                }
                currentTypes.pop_back();
                break;
            }
            case DeclNode::Kind::METHOD: {
                auto method = cast<Method *>(node);
                currentMethods.push_back(method);
                // Todo: Do something
                currentMethods.pop_back();
                break;
            }
            case DeclNode::Kind::CONSTRUCTOR:
                break;
            case DeclNode::Kind::VARIABLE:
                checkVariable(cast<Variable *>(node));
                break;
            case DeclNode::Kind::TYPE_PARAM:
                checkTypeParam(cast<TypeParam *>(node));
                break;
        }
    }

    void checkNodePurity(DeclNode *node) {
        switch (node->getKind()) {
            case DeclNode::Kind::PACKAGE: {
                auto package = cast<Package *>(node);
                for (auto child : package->getChildren()) {
                    switch (child->getKind()) {
                        case DeclNode::Kind::SCOPE:
                            reportError(cast<Scope *>(child)->getCtx(), "not allowed as a top-level declaration");
                            break;
                        case DeclNode::Kind::CONSTRUCTOR:
                            reportError(cast<Constructor *>(child)->getCtx(), "not allowed as a top-level declaration");
                            break;
                        case DeclNode::Kind::TYPE_PARAM:
                            reportError(cast<TypeParam *>(child)->getCtx(), "not allowed as a top-level declaration");
                            break;
                        default:
                            break;
                    }
                    checkNodePurity(child);
                }
                break;
            }
            case DeclNode::Kind::SCOPE: {
                auto scope = cast<Scope *>(node);
                for (auto child : scope->getChildren()) checkNodePurity(child);
                break;
            }
            case DeclNode::Kind::TYPE: {
                Type *type = cast<Type *>(node);
                switch (type->getTypeKind()) {
                    case Type::Kind::INTERFACE:
                        for (auto child : type->getChildren()) {
                            switch (child->getKind()) {
                                case DeclNode::Kind::TYPE:
                                    reportError(DeclNode::getCtx(child), "not allowed in an interface declaration");
                                    break;
                                case DeclNode::Kind::CONSTRUCTOR:
                                    reportError(DeclNode::getCtx(child),
                                                "constructor not allowed in an interface declaration");
                                    break;
                                case DeclNode::Kind::VARIABLE:
                                    if (child->getModifiers().size() != 3)
                                        reportError(DeclNode::getCtx(child),
                                                    "only public static final fields are allowed in an interface declaration");
                                    else
                                        for (auto modifier : child->getModifiers()) {
                                            if (modifier->getText() != "public" || modifier->getText() != "static" ||
                                                modifier->getText() != "final")
                                                reportError(DeclNode::getCtx(child),
                                                            "only public static final fields are allowed in an interface declaration");
                                        }
                                    break;
                                default:
                                    break;
                            }
                        }
                        break;
                    case Type::Kind::ENUM:
                        for (auto child : type->getChildren()) {
                            switch (child->getKind()) {
                                case DeclNode::Kind::TYPE:
                                    reportError(DeclNode::getCtx(child), "not allowed in an enum declaration");
                                    break;
                                default:
                                    break;
                            }
                        }
                        break;
                    default:
                        break;
                }
                for (auto child : type->getChildren()) {
                    switch (child->getKind()) {
                        case DeclNode::Kind::SCOPE:
                            reportError(cast<Scope *>(child)->getCtx(),
                                        "scope not allowed in a class-level declaration");
                            break;
                        default:
                            break;
                    }
                    checkNodePurity(child);
                }
                break;
            }
            case DeclNode::Kind::METHOD: {
                auto method = cast<Method *>(node);
                for (auto child : method->getChildren()) checkNodePurity(child);
                break;
            }
            case DeclNode::Kind::CONSTRUCTOR: {
                auto constructor = cast<Constructor *>(node);
                for (auto child : constructor->getChildren()) checkNodePurity(child);
                break;
            }
            default:
                break;
        }
    }

    std::any visitCompilationUnit(SpadeParser::CompilationUnitContext *ctx) override {
        if (ctx->packageStmt() == null) {
            currentPackages.push_back(new Package(null));
            tree = new DeclTree(currentPackages.back());
        } else
            visitPackageStmt(ctx->packageStmt());

        for (auto decl : ctx->declaration()) visitDeclaration(decl);

        // Reset everything
        currentPackages.clear();
        currentTypes.clear();
        currentMethods.clear();
        currentScopes.clear();

        checkNodePurity(tree->getRoot());

        checkingStarted = true;
        traverseDeclNode(tree->getRoot());
        checkingStarted = false;

        return null;
    }

    std::any visitPackageStmt(SpadeParser::PackageStmtContext *ctx) override {
        auto list = any_cast<vector<antlr4::Token *>>(visitReference(ctx->reference()));
        for (int i = 0; i < list.size(); ++i) {
            auto item = list[i];
            if (tree == null) {
                currentPackages.push_back(new Package(item));
                tree = new DeclTree(currentPackages.back());
            } else {
                auto package = new Package(item);
                currentPackages.back()->addChild(package);
                currentPackages.push_back(package);
            }
        }
        return null;
    }

    std::any visitImportStmt(SpadeParser::ImportStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitDeclaration(SpadeParser::DeclarationContext *ctx) override {
        auto modifiers = any_cast<vector<antlr4::Token *>>(visitModifiers(ctx->modifiers()));
        DeclNode *decl = null;
        if (ctx->classDecl() != null)
            decl = any_cast<DeclNode *>(visitClassDecl(ctx->classDecl()));
        else if (ctx->interfaceDecl() != null)
            decl = any_cast<DeclNode *>(visitInterfaceDecl(ctx->interfaceDecl()));
        else if (ctx->enumDecl() != null)
            decl = any_cast<DeclNode *>(visitEnumDecl(ctx->enumDecl()));
        else if (ctx->annoDecl() != null)
            decl = any_cast<DeclNode *>(visitAnnoDecl(ctx->annoDecl()));
        else if (ctx->functionDecl() != null)
            decl = any_cast<DeclNode *>(visitFunctionDecl(ctx->functionDecl()));
        else if (ctx->varDecl() != null)
            decl = any_cast<DeclNode *>(visitVarDecl(ctx->varDecl()));
        decl->setModifiers(modifiers);
        return decl;
    }

    std::any visitEnumDecl(SpadeParser::EnumDeclContext *ctx) override {
        if (!checkingStarted) {
            auto *decl = new Enum(ctx);
            currentTypes.push_back(decl);

            for (auto member : ctx->memberDecl()) {
                visitMemberDecl(member);
            }

            currentTypes.pop_back();
            if (!currentMethods.empty())
                currentScopes.back()->addChild(decl);
            else if (currentTypes.back() != null)
                currentTypes.back()->addChild(decl);
            else
                currentPackages.back()->addChild(decl);
            return cast<DeclNode *>(decl);
        } else {
            auto enumClass = cast<Enum *>(currentTypes.back());
            checkModifiers(enumClass);
            for (auto parent : ctx->parentList()->parent()) {
                Type *super = checkType(parent->reference());
                try {
                    enumClass->getImplements().push_back(cast<Interface *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not an interface");
                }
            }
            for (auto child : enumClass->getChildren()) traverseDeclNode(child);
            return null;
        }
    }

    std::any visitEnumList(SpadeParser::EnumListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitEnumerator(SpadeParser::EnumeratorContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAnnoDecl(SpadeParser::AnnoDeclContext *ctx) override {
        if (!checkingStarted) {
            auto *decl = new Annotation(ctx);
            currentTypes.push_back(decl);

            visitDeclName(ctx->declName());
            for (auto member : ctx->memberDecl()) {
                visitMemberDecl(member);
            }

            currentTypes.pop_back();
            if (!currentMethods.empty())
                currentScopes.back()->addChild(decl);
            else if (currentTypes.back() != null)
                currentTypes.back()->addChild(decl);
            else
                currentPackages.back()->addChild(decl);
            return cast<DeclNode *>(decl);
        } else {
            auto annotation = cast<Annotation *>(currentTypes.back());
            checkModifiers(annotation);
            if (ctx->parent()) {
                Type *super = checkType(ctx->parent()->reference());
                try {
                    annotation->setExtends(cast<Annotation *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not an annotation");
                }
            }
            for (auto parent : ctx->parentList()->parent()) {
                Type *super = checkType(parent->reference());
                try {
                    annotation->getImplements().push_back(cast<Interface *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not an interface");
                }
            }
            for (auto child : annotation->getChildren()) traverseDeclNode(child);
            return null;
        }
    }

    std::any visitInterfaceDecl(SpadeParser::InterfaceDeclContext *ctx) override {
        if (!checkingStarted) {
            auto *decl = new Interface(ctx);
            currentTypes.push_back(decl);

            visitDeclName(ctx->declName());
            for (auto member : ctx->memberDecl()) {
                visitMemberDecl(member);
            }

            currentTypes.pop_back();
            if (!currentMethods.empty())
                currentScopes.back()->addChild(decl);
            else if (currentTypes.back() != null)
                currentTypes.back()->addChild(decl);
            else
                currentPackages.back()->addChild(decl);
            return cast<DeclNode *>(decl);
        } else {
            auto interface = cast<Interface *>(currentTypes.back());
            checkModifiers(interface);
            for (auto parent : ctx->parentList()->parent()) {
                Type *super = checkType(parent->reference());
                try {
                    interface->getImplements().push_back(cast<Interface *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not an interface");
                }
            }
            for (auto child : interface->getChildren()) traverseDeclNode(child);
            return null;
        }
    }

    std::any visitClassDecl(SpadeParser::ClassDeclContext *ctx) override {
        if (!checkingStarted) {
            auto *decl = new Class(ctx);
            currentTypes.push_back(decl);

            visitDeclName(ctx->declName());
            for (auto member : ctx->memberDecl()) {
                visitMemberDecl(member);
            }

            currentTypes.pop_back();
            if (!currentMethods.empty())
                currentScopes.back()->addChild(decl);
            else if (currentTypes.back() != null)
                currentTypes.back()->addChild(decl);
            else
                currentPackages.back()->addChild(decl);
            return cast<DeclNode *>(decl);
        } else {
            auto klass = cast<Class *>(currentTypes.back());
            checkModifiers(klass);
            if (ctx->parent()) {
                Type *super = checkType(ctx->parent()->reference());
                try {
                    klass->setExtends(cast<Class *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not a class");
                }
            }
            for (auto parent : ctx->parentList()->parent()) {
                Type *super = checkType(parent->reference());
                try {
                    klass->getImplements().push_back(cast<Interface *>(super));
                } catch (const CastError &) {
                    reportError(ctx, "not an interface");
                }
            }
            for (auto child : klass->getChildren()) traverseDeclNode(child);
            return null;
        }
    }

    std::any visitParentList(SpadeParser::ParentListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitParent(SpadeParser::ParentContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitDeclName(SpadeParser::DeclNameContext *ctx) override {
        currentTypes.back()->setName(ctx->IDENTIFIER()->getSymbol());
        auto typeParams = any_cast<vector<SpadeParser::TypeParamContext *>>(visitTypeParams(ctx->typeParams()));
        for (auto typeParam : typeParams) currentTypes.back()->addChild(new TypeParam(typeParam));
        return null;
    }

    std::any visitTypeParams(SpadeParser::TypeParamsContext *ctx) override {
        return ctx->typeParam();
    }

    std::any visitTypeParam(SpadeParser::TypeParamContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitMemberDecl(SpadeParser::MemberDeclContext *ctx) override {
        auto modifiers = any_cast<vector<antlr4::Token *>>(visitModifiers(ctx->modifiers()));
        DeclNode *decl = null;
        if (ctx->classDecl() != null)
            decl = any_cast<DeclNode *>(visitClassDecl(ctx->classDecl()));
        else if (ctx->interfaceDecl() != null)
            decl = any_cast<DeclNode *>(visitInterfaceDecl(ctx->interfaceDecl()));
        else if (ctx->enumDecl() != null)
            decl = any_cast<DeclNode *>(visitEnumDecl(ctx->enumDecl()));
        else if (ctx->fieldDecl() != null)
            decl = any_cast<DeclNode *>(visitFieldDecl(ctx->fieldDecl()));
        else if (ctx->methodDecl() != null)
            decl = any_cast<DeclNode *>(visitMethodDecl(ctx->methodDecl()));
        else if (ctx->constructorDecl() != null)
            decl = any_cast<DeclNode *>(visitConstructorDecl(ctx->constructorDecl()));
        decl->setModifiers(modifiers);
        return decl;
    }

    std::any visitFieldDecl(SpadeParser::FieldDeclContext *ctx) override {
        auto decl = new Variable(ctx->name(), ctx->expr(), ctx->CONST() == null, Variable::VarKind::FIELD);
        currentTypes.back()->addChild(decl);
        return cast<DeclNode *>(decl);
    }

    std::any visitMethodDecl(SpadeParser::MethodDeclContext *ctx) override {
        auto decl = new Method(ctx);
        if (currentTypes.empty())
            currentPackages.back()->addChild(decl);
        else
            currentTypes.back()->addChild(decl);
        return cast<DeclNode *>(decl);
    }

    std::any visitConstructorDecl(SpadeParser::ConstructorDeclContext *ctx) override {
        auto decl = new Constructor(ctx);
        currentTypes.back()->addChild(decl);
        return decl;
    }

    std::any visitModifiers(SpadeParser::ModifiersContext *ctx) override {
        vector<antlr4::Token *> tokens;
        for (auto modifier : ctx->ABSTRACT()) tokens.push_back(modifier->getSymbol());
        for (auto modifier : ctx->FINAL()) tokens.push_back(modifier->getSymbol());
        for (auto modifier : ctx->STATIC()) tokens.push_back(modifier->getSymbol());
        for (auto modifier : ctx->INLINE()) tokens.push_back(modifier->getSymbol());
        for (auto accessors : ctx->accessors())
            for (auto accessor :
                 any_cast<vector<antlr4::Token *>>(visitAccessors(accessors)))
                tokens.push_back(accessor);

        map<antlr4::Token *, int> table;
        for (auto token : tokens)
            try {
                table.at(token)++;
            } catch (std::out_of_range &) {
                table[token] = 1;
            }

        for (auto [token, occurrences] : table)
            if (occurrences > 1)
                reportError(token, "occurred more than 1 time");

        return tokens;
    }

    std::any visitAccessors(SpadeParser::AccessorsContext *ctx) override {
        vector<antlr4::Token *> tokens;
        if (ctx->PRIVATE() != null)
            tokens.push_back(ctx->PRIVATE()->getSymbol());
        else if (ctx->INTERNAL() != null)
            tokens.push_back(ctx->INTERNAL()->getSymbol());
        else if (ctx->PROTECTED() != null)
            tokens.push_back(ctx->PROTECTED()->getSymbol());
        else if (ctx->PUBLIC() != null)
            tokens.push_back(ctx->PUBLIC()->getSymbol());
        return tokens;
    }

    std::any visitFunctionDecl(SpadeParser::FunctionDeclContext *ctx) override {
        return visitMethodDecl(ctx->methodDecl());
    }

    std::any visitDefinition(SpadeParser::DefinitionContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitParams(SpadeParser::ParamsContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitParamList(SpadeParser::ParamListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitParam(SpadeParser::ParamContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitVarDecl(SpadeParser::VarDeclContext *ctx) override {
        auto decl = new Variable(ctx->name(), ctx->expr(),
                                 ctx->CONST() == null, !currentMethods.empty() ? Variable::VarKind::LOCAL : Variable::VarKind::GLOBAL);
        if (!currentMethods.empty())
            currentScopes.back()->addChild(decl);
        else
            currentPackages.back()->addChild(decl);
        return decl;
    }

    std::any visitName(SpadeParser::NameContext *ctx) override {
        return ctx->type() ? checkType(ctx->type()) : null;
    }

    std::any visitStmts(SpadeParser::StmtsContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitIfStmt(SpadeParser::IfStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitWhileStmt(SpadeParser::WhileStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitDoStmt(SpadeParser::DoStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitForStmt(SpadeParser::ForStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitForeachStmt(SpadeParser::ForeachStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitMatchStmt(SpadeParser::MatchStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitThrowStmt(SpadeParser::ThrowStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitTryStmt(SpadeParser::TryStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitContinueStmt(SpadeParser::ContinueStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBreakStmt(SpadeParser::BreakStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitReturnStmt(SpadeParser::ReturnStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitYieldStmt(SpadeParser::YieldStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitNoStmt(SpadeParser::NoStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitExprStmt(SpadeParser::ExprStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitDestructDecl(SpadeParser::DestructDeclContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitDestruct(SpadeParser::DestructContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBlock(SpadeParser::BlockContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitMatchCase(SpadeParser::MatchCaseContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitCatchStmt(SpadeParser::CatchStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitFinallyStmt(SpadeParser::FinallyStmtContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBody(SpadeParser::BodyContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitElse(SpadeParser::ElseContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitExpr(SpadeParser::ExprContext *ctx) {
#define DIRECT(type) else if (is<SpadeParser::type##ExprContext *>(ctx)) return visit##type##Expr(cast<SpadeParser::type##ExprContext *>(ctx))
        if (is<SpadeParser::UnaryExprContext *>(ctx))
            return visitUnaryExpr(cast<SpadeParser::UnaryExprContext *>(ctx));
        DIRECT(Elvis);
        DIRECT(Cast);
        DIRECT(Power);
        DIRECT(Factor);
        DIRECT(Term);
        DIRECT(Shift);
        DIRECT(BitAnd);
        DIRECT(BitXor);
        DIRECT(BitOr);
        DIRECT(Relational);
        DIRECT(Conditional);
        DIRECT(Not);
        DIRECT(And);
        DIRECT(Or);
        DIRECT(Ternary);
        DIRECT(Lambda);
        DIRECT(Assign);
        return null;
#undef DIRECT
    }

    std::any visitUnaryExpr(SpadeParser::UnaryExprContext *ctx) override {
        switch (ctx->op->getType()) {
            case SpadeLexer::BANG:
                break;
            case SpadeLexer::TILDE:
                break;
            case SpadeLexer::DASH:
                break;
            case SpadeLexer::PLUS:
                break;
            default:
                return visitPostfix(ctx->postfix());
        }
        return visitChildren(ctx);
    }

    std::any visitElvisExpr(SpadeParser::ElvisExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitCastExpr(SpadeParser::CastExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitPowerExpr(SpadeParser::PowerExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitFactorExpr(SpadeParser::FactorExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitTermExpr(SpadeParser::TermExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitShiftExpr(SpadeParser::ShiftExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBitAndExpr(SpadeParser::BitAndExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBitXorExpr(SpadeParser::BitXorExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitBitOrExpr(SpadeParser::BitOrExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitRelationalExpr(SpadeParser::RelationalExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitConditionalExpr(SpadeParser::ConditionalExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitNotExpr(SpadeParser::NotExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAndExpr(SpadeParser::AndExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitOrExpr(SpadeParser::OrExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitTernaryExpr(SpadeParser::TernaryExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitLambdaExpr(SpadeParser::LambdaExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAssignExpr(SpadeParser::AssignExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAssigneeList(SpadeParser::AssigneeListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAssignee(SpadeParser::AssigneeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitAssignOperator(SpadeParser::AssignOperatorContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitPrimary(SpadeParser::PrimaryContext *ctx) {
#define DIRECT(type) else if (is<SpadeParser::type##ExprContext *>(ctx)) return visit##type##Expr(cast<SpadeParser::type##ExprContext *>(ctx))
        if (is<SpadeParser::ConstantExprContext *>(ctx))
            return visitConstantExpr(cast<SpadeParser::ConstantExprContext *>(ctx));
        DIRECT(Builder);
        DIRECT(Super);
        DIRECT(This);
        DIRECT(Group);
        DIRECT(Tuple);
        DIRECT(Set);
        DIRECT(Map);
        DIRECT(List);
        DIRECT(Type);
        return null;
#undef DIRECT
    }

    std::any visitPostfix(SpadeParser::PostfixContext *ctx) {
#define DIRECT(type) else if (is<SpadeParser::Postfix##type##Context *>(ctx)) return visitPostfix##type(cast<SpadeParser::Postfix##type##Context *>(ctx))
        if (is<SpadeParser::PostfixPrimaryContext *>(ctx))
            return visitPostfixPrimary(cast<SpadeParser::PostfixPrimaryContext *>(ctx));
        DIRECT(Dot);
        DIRECT(Generic);
        DIRECT(Call);
        DIRECT(Indexer);
        DIRECT(Block);
        return null;
#undef DIRECT
    }

    vector<DeclNode *> getAccessibleMembers(vector<DeclNode *> nodes) {
        auto type = currentTypes.back();
        auto package = currentPackages.back();
        vector<DeclNode *> members;
        for (auto node : nodes) {
            auto accessibility = node->getAccessibility();
            switch (node->getAccessibility()) {
                case DeclNode::Accessor::PRIVATE:
                    if (type == node->getParent()) members.push_back(node);
                    break;
                case DeclNode::Accessor::INTERNAL:
                    if (type->isSuperOf(cast<Type *>(node->getParent())) && package == node->getPackage())
                        members.push_back(node);
                    break;
                case DeclNode::Accessor::PACKAGE_PRIVATE:
                    if (package == node->getPackage()) members.push_back(node);
                    break;
                case DeclNode::Accessor::PROTECTED:
                    if (package == node->getPackage() || type->isSuperOf(cast<Type *>(node->getParent())))
                        members.push_back(node);
                    break;
                case DeclNode::Accessor::PUBLIC:
                    members.push_back(node);
                    break;
            }
        }
        return members;
    }

    std::any visitPostfixPrimary(SpadeParser::PostfixPrimaryContext *ctx) override {
        return vector<DeclNode *>{any_cast<DeclNode *>(visitPrimary(ctx->primary()))};
    }

    std::any visitPostfixDot(SpadeParser::PostfixDotContext *ctx) override {
        auto node = any_cast<DeclNode *>(visitPostfix(ctx->postfix()));
        auto members = node->getMembers(ctx->IDENTIFIER()->getText());
        if (members.empty()) reportError(ctx, "cannot be referenced");
        members = getAccessibleMembers(members);
        if (members.empty()) reportError(ctx, "not accessible");
        return members;
    }

    std::any visitPostfixGeneric(SpadeParser::PostfixGenericContext *ctx) override {
        auto type = any_cast<Type *>(visitPostfix(ctx->postfix()));
        auto typeArgs = visitTypeArgs(ctx->typeArgs());
        return visitChildren(ctx);
    }

    std::any visitPostfixCall(SpadeParser::PostfixCallContext *ctx) override {
        auto type = any_cast<Type *>(visitPostfix(ctx->postfix()));
        return visitChildren(ctx);
    }

    std::any visitPostfixIndexer(SpadeParser::PostfixIndexerContext *ctx) override {
        auto type = any_cast<Type *>(visitPostfix(ctx->postfix()));
        return visitChildren(ctx);
    }

    std::any visitPostfixBlock(SpadeParser::PostfixBlockContext *ctx) override {
        auto type = any_cast<Type *>(visitPostfix(ctx->postfix()));
        return visitChildren(ctx);
    }

    std::any visitArgs(SpadeParser::ArgsContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitArg(SpadeParser::ArgContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitIndexer(SpadeParser::IndexerContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitSlice(SpadeParser::SliceContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitConstantExpr(SpadeParser::ConstantExprContext *ctx) override {
        return visitConstant(ctx->constant());
    }

    std::any visitBuilderExpr(SpadeParser::BuilderExprContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitSuperExpr(SpadeParser::SuperExprContext *ctx) override {
        if (currentTypes.empty()) reportError(ctx, "'super' expression must be used inside a class");
        auto type = currentTypes.back();
        auto superTypes = Type::getSuperTypes(type);
        switch (type->getTypeKind()) {
            case Type::Kind::CLASS:
                if (ctx->reference() != null) {
                    auto referredType = checkType(ctx->reference());
                    if (std::find(superTypes.begin(), superTypes.end(), referredType) != superTypes.end())
                        reportError(ctx->reference(), format("not a super-class of %s", type->getSign().c_str()));
                    else
                        return referredType;
                } else
                    return cast<Class *>(type)->getExtends();
                break;
            case Type::Kind::ANNOTATION:
                if (ctx->reference() != null) {
                    auto referredType = checkType(ctx->reference());
                    if (std::find(superTypes.begin(), superTypes.end(), referredType) != superTypes.end())
                        reportError(ctx->reference(), format("not a super-class of %s", type->getSign().c_str()));
                    else
                        return referredType;
                } else
                    return cast<Annotation *>(type)->getExtends();
                break;
            case Type::Kind::INTERFACE:
                if (ctx->reference() != null) {
                    auto referredType = checkType(ctx->reference());
                    if (std::find(superTypes.begin(), superTypes.end(), referredType) != superTypes.end())
                        reportError(ctx->reference(), format("not a super-interface of %s", type->getSign().c_str()));
                    else
                        return referredType;
                } else {
                    if (superTypes.size() == 1)
                        return superTypes[0];
                    else
                        reportError(ctx, "cannot be determined which super-interface to infer");
                }
                break;
            case Type::Kind::ENUM:
                if (ctx->reference() != null) {
                    auto referredType = checkType(ctx->reference());
                    if (std::find(superTypes.begin(), superTypes.end(), referredType) != superTypes.end())
                        reportError(ctx->reference(), format("not a super-interface of %s", type->getSign().c_str()));
                    else
                        return referredType;
                } else {
                    if (superTypes.size() == 1)
                        return superTypes[0];
                    else
                        reportError(ctx, "cannot be determined which super-interface to infer");
                }
                break;
        }
        return null;
    }

    std::any visitThisExpr(SpadeParser::ThisExprContext *ctx) override {
        if (currentTypes.empty()) reportError(ctx, "'this' expression must be used inside a class");
        return currentTypes.back();
    }

    std::any visitGroupExpr(SpadeParser::GroupExprContext *ctx) override {
        return visitExpr(ctx->expr());
    }

    std::any visitTupleExpr(SpadeParser::TupleExprContext *ctx) override {
        if (ctx->items() != null) return visitItems(ctx->items());
        return null;
    }

    std::any visitSetExpr(SpadeParser::SetExprContext *ctx) override {
        return visitItems(ctx->items());
    }

    std::any visitMapExpr(SpadeParser::MapExprContext *ctx) override {
        if (ctx->entries() != null) return visitEntries(ctx->entries());
        return null;
    }

    std::any visitListExpr(SpadeParser::ListExprContext *ctx) override {
        if (ctx->items() != null) return visitItems(ctx->items());
        return null;
    }

    std::any visitTypeExpr(SpadeParser::TypeExprContext *ctx) override {
        // todo This does not return the type of the type expression
        return checkType(ctx->type());
    }

    std::any visitConstant(SpadeParser::ConstantContext *ctx) override {
        if (ctx->TRUE() != null || ctx->FALSE() != null)
            return Type::BOOL;
        else if (ctx->NULL_() != null)
            return Type::NULL_TYPE;
        else if (ctx->literal() != null)
            return visitLiteral(ctx->literal());
        return null;
    }

    DeclNode *getCurrentNode() {
        DeclNode *currentNode = null;
        if (!currentScopes.empty())
            currentNode = currentScopes.back();
        else if (!currentMethods.empty())
            currentNode = currentMethods.back();
        else if (!currentTypes.empty())
            currentNode = currentTypes.back();
        else if (!currentPackages.empty())
            currentNode = currentPackages.back();
        return currentNode;
    }

    std::any visitLiteral(SpadeParser::LiteralContext *ctx) override {
        if (ctx->INTEGER() != null)
            return Type::INT;
        else if (ctx->FLOAT() != null)
            return Type::FLOAT;
        else if (ctx->STRING() != null)
            return Type::STRING;
        else if (ctx->IDENTIFIER() != null) {
            auto name = ctx->IDENTIFIER()->getText();
            for (DeclNode *node = getCurrentNode(); node != null; node = node->getParent()) {
                auto members = node->getMembers(name);
                if (members.empty()) continue;
                auto member = members[0];
                // todo add type support
                if (is<Variable *>(member)) return cast<Variable *>(member)->getType();
            }
        }
        return null;
    }

    std::any visitObjectBuilder(SpadeParser::ObjectBuilderContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitItems(SpadeParser::ItemsContext *ctx) override {
        return ctx->expr();
    }

    std::any visitEntries(SpadeParser::EntriesContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitEntry(SpadeParser::EntryContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitLiteralType(SpadeParser::LiteralTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitTypeofType(SpadeParser::TypeofTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitNullableType(SpadeParser::NullableTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitIntersectionType(SpadeParser::IntersectionTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitReferenceType(SpadeParser::ReferenceTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitFunctionType(SpadeParser::FunctionTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitObjectType(SpadeParser::ObjectTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitUnionType(SpadeParser::UnionTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitReference(SpadeParser::ReferenceContext *ctx) override {
        vector<antlr4::Token *> tokens;
        tokens.reserve(ctx->IDENTIFIER().size());
        for (auto identifier : ctx->IDENTIFIER()) {
            tokens.push_back(identifier->getSymbol());
        }
        return tokens;
    }

    std::any visitTypeArgs(SpadeParser::TypeArgsContext *ctx) override {
        vector<Type *> types;
        types.reserve(ctx->typeArg().size());
        for (auto typeArgCtx : ctx->typeArg()) {
            types.push_back(any_cast<Type *>(visitTypeArg(typeArgCtx)));
        }
        return visitChildren(ctx);
    }

    std::any visitTypeArg(SpadeParser::TypeArgContext *ctx) override {
        // TODO: add support for out and in
        return checkType(ctx->type());
    }

    std::any visitParamTypes(SpadeParser::ParamTypesContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitParamType(SpadeParser::ParamTypeContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitTypeList(SpadeParser::TypeListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitMemberTypeList(SpadeParser::MemberTypeListContext *ctx) override {
        return visitChildren(ctx);
    }

    std::any visitMemberType(SpadeParser::MemberTypeContext *ctx) override {
        return visitChildren(ctx);
    }
};
